### ISSUE TITLE
artifacts-gce-image-test: Failed to create devices

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-machine-image#91] opened 2021-01-11 11:14 UTC
**System under test**

Actual gce image used: scylla-4-4-dev-build-2021-01-11t09-05-45
AWS region: us-east1
Instance type: n1-standard-2
Scylla packages installed:
scylla-conf-4.4.dev-0.20210111.3aa80f47fec.x86_64
scylla-kernel-conf-4.4.dev-0.20210111.3aa80f47fec.x86_64
scylla-tools-4.4.dev-0.20210111.3aa80f47fec.noarch
scylla-debuginfo-4.4.dev-0.20210111.3aa80f47fec.x86_64
scylla-python3-4.4.dev-0.20210111.3aa80f47fec.x86_64
scylla-node-exporter-4.4.dev-0.20210111.3aa80f47fec.x86_64
scylla-tools-core-4.4.dev-0.20210111.3aa80f47fec.noarch
scylla-jmx-4.4.dev-0.20210111.3aa80f47fec.noarch
scylla-machine-image-4.4.dev-20210111.b23ecb53ef.noarch
scylla-server-4.4.dev-0.20210111.3aa80f47fec.x86_64
scylla-4.4.dev-0.20210111.3aa80f47fec.x86_64

[Job](https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-gce-image-test/59)

Test: artifacts-gce-image-test

Failed to create devices:
```
Jan 11 09:21:07 artifacts-gce-image-jenkins-db-node-d0e9db1d-0-1 scylla_image_setup[744]: nvme0n1 is not found
Jan 11 09:21:07 artifacts-gce-image-jenkins-db-node-d0e9db1d-0-1 scylla_image_setup[744]: Traceback (most recent call last):
Jan 11 09:21:07 artifacts-gce-image-jenkins-db-node-d0e9db1d-0-1 scylla_image_setup[744]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_create_devices", line 74, in <module>
Jan 11 09:21:07 artifacts-gce-image-jenkins-db-node-d0e9db1d-0-1 scylla_image_setup[744]:     create_raid(disk_devices)
Jan 11 09:21:07 artifacts-gce-image-jenkins-db-node-d0e9db1d-0-1 scylla_image_setup[744]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_create_devices", line 33, in create_raid
Jan 11 09:21:07 artifacts-gce-image-jenkins-db-node-d0e9db1d-0-1 scylla_image_setup[744]:     run(["/opt/scylladb/scripts/scylla_raid_setup", "--raiddev", "/dev/md0", "--disks", ",".join(devices),
Jan 11 09:21:07 artifacts-gce-image-jenkins-db-node-d0e9db1d-0-1 scylla_image_setup[744]:   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
Jan 11 09:21:07 artifacts-gce-image-jenkins-db-node-d0e9db1d-0-1 scylla_image_setup[744]:     raise CalledProcessError(retcode, process.args,
Jan 11 09:21:07 artifacts-gce-image-jenkins-db-node-d0e9db1d-0-1 scylla_image_setup[744]: subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_raid_setup', '--raiddev', '/dev/md0', '--disks', 'nvme0n1', '--root', '/var/lib/scylla', '--volume-role', 'all', '--update-fstab']' returned non-zero exit status 1.
Jan 11 09:21:07 artifacts-gce-image-jenkins-db-node-d0e9db1d-0-1 scylla_image_setup[744]: 2021-01-11 09:21:07,037 - [scylla_configure] - ERROR - Failed to create devices: Command '/opt/scylladb/scylla-machine-image/scylla_create_devices ' returned non-zero exit status 1.
Jan 11 09:21:07 artifacts-gce-image-jenkins-db-node-d0e9db1d-0-1 scylla_image_setup[744]: Failed to create devices: Command '/opt/scylladb/scylla-machine-image/scylla_create_devices ' returned non-zero exit status 1.
Jan 11 09:21:07 artifacts-gce-image-jenkins-db-node-d0e9db1d-0-1 scylla_image_setup[744]: Traceback (most recent call last):
Jan 11 09:21:07 artifacts-gce-image-jenkins-db-node-d0e9db1d-0-1 scylla_image_setup[744]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_image_setup", line 26, in <module>
Jan 11 09:21:07 artifacts-gce-image-jenkins-db-node-d0e9db1d-0-1 scylla_image_setup[744]:     run('/opt/scylladb/scylla-machine-image/scylla_configure.py', shell=True, check=True)
Jan 11 09:21:07 artifacts-gce-image-jenkins-db-node-d0e9db1d-0-1 scylla_image_setup[744]:   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
Jan 11 09:21:07 artifacts-gce-image-jenkins-db-node-d0e9db1d-0-1 scylla_image_setup[744]:     raise CalledProcessError(retcode, process.args,
Jan 11 09:21:07 artifacts-gce-image-jenkins-db-node-d0e9db1d-0-1 scylla_image_setup[744]: subprocess.CalledProcessError: Command '/opt/scylladb/scylla-machine-image/scylla_configure.py' returned non-zero exit status 1.
```

Hydra commands:
```
Restore Monitor Stack command: $ hydra investigate show-monitor d0e9db1d-39c1-4e61-accd-6af00c8c6f32
Show all stored logs command: $ hydra investigate show-logs d0e9db1d-39c1-4e61-accd-6af00c8c6f32
```

Logs:
```
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/d0e9db1d-39c1-4e61-accd-6af00c8c6f32/20210111_092731/db-cluster-d0e9db1d.zip
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/d0e9db1d-39c1-4e61-accd-6af00c8c6f32/20210111_092731/sct-runner-d0e9db1d.zip
```

**Comment by fruch** [comment] 2021-01-11 11:24
@aleksbykov can you take a look, this sound like the recent #88 might be the cause of it.

**Comment by aleksbykov** [comment] 2021-01-11 11:35
@fruch , yes, you right. this issue was triggered by this commit. 
Prepare a fix

**Comment by slivne** [comment] 2021-01-13 12:07
@fruch did the patch fix the problem - can we close this issue ?

**Comment by fruch** [comment] 2021-01-18 12:40
> @fruch did the patch fix the problem - can we close this issue ?

yes it did, we can close (wasn't close automatically, cause it was merged directly to master by mistake)

**Closed by fruch** 2021-01-18 12:40 UTC
