### ISSUE TITLE
Mistype in method call for ec2 instance in scylla-machine-image/libexec/scylla_login

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-machine-image#335] opened 2022-04-12 15:23 UTC
Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-1021-aws x86_64)
```
Version:
        5.0.rc3-0.20220406.f92622e0d
Nodetool:
        nodetool help
CQL Shell:
        cqlsh
More documentation available at: 
        https://docs.scylladb.com/
By default, Scylla sends certain information about this node to a data collection server. For more details, see https://www.scylladb.com/privacy/

Traceback (most recent call last):
  File "/opt/scylladb/scylla-machine-image/libexec/scylla_login", line 122, in <module>
    non_root_disks = cloud_instance.ehpemeral_disks() + cloud_instance.ebs_disks()
AttributeError: 'aws_instance' object has no attribute 'ehpemeral_disks'
```

Should be cloud_instance.ephemeral_disks()

**Comment by michoecho** [comment] 2022-10-03 09:55
Fixed by fc4357a740ba415fdcd1054c01440228c1a6cd88 (present in 5.1rc0), but not fixed in 5.0.
If there are no plans to fix it in 5.0, consider closing this issue.

**Comment by tarzanek** [comment] 2023-01-17 20:50
2022.1.3 has it too, this should be fixed / backported, shouldn't it? @syuu1228 @yaronkaikov

**Comment by mykaul** [comment] 2023-01-18 07:46
> 2022.1.3 has it too, this should be fixed / backported, shouldn't it? @syuu1228 @yaronkaikov

 Any customers impacted? What's the customer impact?

**Comment by yaronkaikov** [comment] 2023-01-22 20:15
@tarzanek, AFAIU has no impact on a customer.

**Comment by yaronkaikov** [comment] 2023-01-23 10:07
@mykaul Although we don't have a specific customer hitting this, it seems like a safe/easy backport. 2022.1 is going to be with us for a while, WDYT?

**Comment by mykaul** [comment] 2023-01-23 12:48
> @mykaul Although we don't have a specific customer hitting this, it seems like a safe/easy backport. 2022.1 is going to be with us for a while, WDYT?

Sure, I'm not against it if it's an easy and safe backport.

**Comment by yaronkaikov** [comment] 2023-01-25 04:44
Backported to 5.0 (2022.1 will get in in for the next release)

**Comment by syuu1228** [comment] 2023-01-26 09:24
@yaronkaikov 3d015927ca26cd690b9d97b32ee56fb35b226618 and fc4357a740ba415fdcd1054c01440228c1a6cd88 are bug fix of 5f66a515ba48f880b9fe4fdf5fc59518d004cdd7, which is introduced from 5.1. So backporting these bug fix patches to 5.0 would break the script.
Same on enterprise 2022.1, it doesn't have 5f66a515ba48f880b9fe4fdf5fc59518d004cdd7, it introduced from 2022.2 with bug fix patches.

**Comment by yaronkaikov** [comment] 2023-01-26 11:58
@syuu1228 Thanks, I will revert those changes.

**Comment by yaronkaikov** [comment] 2023-01-26 11:58
@syuu1228 Can you please verify what is broken in 5.0 and 2022.1 and send an updated patch ?

**Comment by tarzanek** [comment] 2023-01-26 13:32
hmm, also @syuu1228 I'd expect most IDEs these days have refactoring with searching for usage (and patching it for you too)
(at least Idea does)

**Comment by syuu1228** [comment] 2023-01-26 15:29
> @syuu1228 Can you please verify what is broken in 5.0 and 2022.1 and send an updated patch ?

Couldn't reproduce the issue on 5.0.9 AMI:
```
Welcome to Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-1027-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Thu Jan 26 13:03:33 UTC 2023

  System load:  1.1                Processes:             147
  Usage of /:   14.2% of 28.89GB   Users logged in:       0
  Memory usage: 1%                 IPv4 address for eth0: 10.0.1.60
  Swap usage:   0%



The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.


   _____            _ _       _____  ____  
  / ____|          | | |     |  __ \|  _ \ 
 | (___   ___ _   _| | | __ _| |  | | |_) |
  \___ \ / __| | | | | |/ _` | |  | |  _ < 
  ____) | (__| |_| | | | (_| | |__| | |_) |
 |_____/ \___|\__, |_|_|\__,_|_____/|____/ 
               __/ |                       
              |___/                        

Version:
        5.0.9-0.20230111.94b8baa79
Nodetool:
        nodetool help
CQL Shell:
        cqlsh
More documentation available at: 
        https://docs.scylladb.com/
By default, Scylla sends certain information about this node to a data collection server. For more details, see https://www.scylladb.com/privacy/

    Constructing RAID volume...

Please wait for the setup to finish. To see its status, run 
 'systemctl status scylla-image-setup'

After the setup has finished, scylla-server service will launch.
To see the status of scylla-server, run 
 'systemctl status scylla-server'

This EC2 instance is optimized for Scylla.
```

Same as Scylla 2021.1.3 AMI:
```
Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1035-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Thu Jan 26 15:24:08 UTC 2023

  System load:  3.0                Processes:             134
  Usage of /:   19.9% of 29.02GB   Users logged in:       0
  Memory usage: 1%                 IPv4 address for eth0: 10.0.1.73
  Swap usage:   0%


9 updates can be applied immediately.
7 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable


The list of available updates is more than a week old.
To check for new updates run: sudo apt update


The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.


   _____            _ _       _____  ____  
  / ____|          | | |     |  __ \|  _ \ 
 | (___   ___ _   _| | | __ _| |  | | |_) |
  \___ \ / __| | | | | |/ _` | |  | |  _ < 
  ____) | (__| |_| | | | (_| | |__| | |_) |
 |_____/ \___|\__, |_|_|\__,_|_____/|____/ 
               __/ |                       
              |___/                        

Version:
       2021.1.3-0.20210708.aec1c25d7
Nodetool:
	nodetool help
CQL Shell:
	cqlsh
More documentation available at: 
	http://www.scylladb.com/doc/
By default, Scylla sends certain information about this node to a data collection server. For information, see http://www.scylladb.com/privacy/

    Constructing RAID volume...

Please wait for setup. To see status, run 
 'systemctl status scylla-image-setup'

After setup finished, scylla-server service will launch.
To see status of scylla-server, run 
 'systemctl status scylla-server'

This EC2 instance is optimized for Scylla.
```

**Comment by yaronkaikov** [comment] 2023-01-29 09:59
> > @syuu1228 Can you please verify what is broken in 5.0 and 2022.1 and send an updated patch ?
> 
> Couldn't reproduce the issue on 5.0.9 AMI:
> 
> ```
> Welcome to Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-1027-aws x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   System information as of Thu Jan 26 13:03:33 UTC 2023
> 
>   System load:  1.1                Processes:             147
>   Usage of /:   14.2% of 28.89GB   Users logged in:       0
>   Memory usage: 1%                 IPv4 address for eth0: 10.0.1.60
>   Swap usage:   0%
> 
> 
> 
> The programs included with the Ubuntu system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
> applicable law.
> 
> 
>    _____            _ _       _____  ____  
>   / ____|          | | |     |  __ \|  _ \ 
>  | (___   ___ _   _| | | __ _| |  | | |_) |
>   \___ \ / __| | | | | |/ _` | |  | |  _ < 
>   ____) | (__| |_| | | | (_| | |__| | |_) |
>  |_____/ \___|\__, |_|_|\__,_|_____/|____/ 
>                __/ |                       
>               |___/                        
> 
> Version:
>         5.0.9-0.20230111.94b8baa79
> Nodetool:
>         nodetool help
> CQL Shell:
>         cqlsh
> More documentation available at: 
>         https://docs.scylladb.com/
> By default, Scylla sends certain information about this node to a data collection server. For more details, see https://www.scylladb.com/privacy/
> 
>     Constructing RAID volume...
> 
> Please wait for the setup to finish. To see its status, run 
>  'systemctl status scylla-image-setup'
> 
> After the setup has finished, scylla-server service will launch.
> To see the status of scylla-server, run 
>  'systemctl status scylla-server'
> 
> This EC2 instance is optimized for Scylla.
> ```
> 
> Same as Scylla 2021.1.3 AMI:
> 
> ```
> Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1035-aws x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   System information as of Thu Jan 26 15:24:08 UTC 2023
> 
>   System load:  3.0                Processes:             134
>   Usage of /:   19.9% of 29.02GB   Users logged in:       0
>   Memory usage: 1%                 IPv4 address for eth0: 10.0.1.73
>   Swap usage:   0%
> 
> 
> 9 updates can be applied immediately.
> 7 of these updates are standard security updates.
> To see these additional updates run: apt list --upgradable
> 
> 
> The list of available updates is more than a week old.
> To check for new updates run: sudo apt update
> 
> 
> The programs included with the Ubuntu system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
> applicable law.
> 
> 
>    _____            _ _       _____  ____  
>   / ____|          | | |     |  __ \|  _ \ 
>  | (___   ___ _   _| | | __ _| |  | | |_) |
>   \___ \ / __| | | | | |/ _` | |  | |  _ < 
>   ____) | (__| |_| | | | (_| | |__| | |_) |
>  |_____/ \___|\__, |_|_|\__,_|_____/|____/ 
>                __/ |                       
>               |___/                        
> 
> Version:
>        2021.1.3-0.20210708.aec1c25d7
> Nodetool:
> 	nodetool help
> CQL Shell:
> 	cqlsh
> More documentation available at: 
> 	http://www.scylladb.com/doc/
> By default, Scylla sends certain information about this node to a data collection server. For information, see http://www.scylladb.com/privacy/
> 
>     Constructing RAID volume...
> 
> Please wait for setup. To see status, run 
>  'systemctl status scylla-image-setup'
> 
> After setup finished, scylla-server service will launch.
> To see status of scylla-server, run 
>  'systemctl status scylla-server'
> 
> This EC2 instance is optimized for Scylla.
> ```

Closing based on @syuu1228 inputs.

**Closed by yaronkaikov** 2023-01-29 09:59 UTC
