### ISSUE TITLE
Add logrotate to our images

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-machine-image#502] opened 2024-01-08 06:46 UTC
Based on https://github.com/scylladb/siren/issues/7370#issuecomment-1230860375

Refs: https://github.com/scylladb/siren/issues/7370

**Comment by fruch** [comment] 2024-01-08 08:19
I thought that rsyslog isn't installed in the images anymore..

**Comment by mykaul** [comment] 2024-01-08 08:35
It has nothing to do with rsyslog - journal logs need to be rotated (as is other logs that might be filling the root disk)

**Comment by syuu1228** [comment] 2024-02-09 11:21
I checked https://github.com/scylladb/siren/issues/7370#issuecomment-1230860375, all of these settings are logrotate settings for rsyslog, but we dropped rsyslog and use journald only, so there's nothing to apply on master image.
(and journald automatically rotate logs unlike rsyslog)

**Comment by mykaul** [comment] 2024-02-11 08:20
> I checked [scylladb/siren#7370 (comment)](https://github.com/scylladb/siren/issues/7370#issuecomment-1230860375), all of these settings are logrotate settings for rsyslog, but we dropped rsyslog and use journald only, so there's nothing to apply on master image. (and journald automatically rotate logs unlike rsyslog)

I think we should tweak its settings - it seem to consume a lot of memory, before rotating. It may be not be rotating enough.

**Comment by syuu1228** [comment] 2024-03-04 09:30
> I think we should tweak its settings - it seem to consume a lot of memory, before rotating. It may be not be rotating enough.

I tried to reproduce this on ScyllaDB 5.4.3 image, but not reproduced.
When I generated very large amount of journal log using `scylla --default-log-level TRACE` with cassandra-stress, systemd-journald only use 0.6% of system memory (about 360MB).
I think we can keep using default settings.

**Comment by syuu1228** [comment] 2024-03-04 09:36
Closing, since there is no issue on the latest version.

**Closed by syuu1228** 2024-03-04 09:36 UTC
Labels: P2

**Comment by mykaul** [comment] 2024-03-04 11:41
@syuu1228 - making sure - are we rotating logs?
